[package]
name = "models"
edition = "2021"
version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
common_utils = { path = "../common" }
