[package]
name = "common_utils"
version.workspace = true
publish = false
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
