name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hustcer/setup-nu@v3
      with:
        check-latest: true
        
    - name: Env
      run: nu envsetup.nu
      
    - name: Build
      run: cargo build --release
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: terra-ps
        path: target/release/*.exe
        
